@php($showTemplateCalculator = true)
@php($showSubcatSections = false)
@php($showRolletCalculator = false)
@php($showRolletProfilePrices = true)
@php($showSeoSection = true)
@php($showInstallationSection = false)
@php($showWorkExamplesEarly = true)
@php($showGateScheme = true)
@php($showDeliveryAfterSeo = true)
@php($calculatorTitle = 'Рассчитать стоимость секционных ворот')
@php($rolletProfilePricesTitle = 'Цены на секционные ворота')
@php($rolletProfilePricesNote = 'В таблицах указаны цены на популярные размеры секционных ворот по профилям RH45N, RH58N и RH77M. Итоговая стоимость уточняется по размерам, комплектации и монтажу.')

@include('front.subcategory-template-1')
