@php($showTemplateCalculator = false)
@php($showSubcatSections = false)
@php($showRolletCalculator = true)
@php($showRolletProfilePrices = true)
@php($showSeoSection = false)
@include('front.subcategory-template-1')
