@php($showTemplateCalculator = false)
@php($showSubcatSections = false)
@php($showRolletCalculator = true)
@php($showRolletProfilePrices = true)
@php($showSeoSection = trim((string) ($subcategory->seo ?? '')) !== '')
@include('front.subcategory-template-1')
