@php($showTemplateCalculator = false)
@php($showSubcatSections = false)
@php($showRolletCalculator = true)
@php($showRolletProfilePrices = true)
@php($showSeoSection = true)
@php($showInstallationSection = false)
@php($showWorkExamplesEarly = true)
@php($showGateScheme = true)
@php($showDeliveryAfterSeo = true)
@php($calculatorTitle = 'Рассчитать стоимость секционных ворот')
@php($rolletCalculatorTitle = 'Рассчитать стоимость секционных ворот')
@php($rolletCalculatorProducts = !empty($firstProduct)
    ? \App\Models\Product::where('subcategory_id', $subcategory->clone_subcategory_id ?: $subcategory->id)
        ->where('model_id', $firstProduct->model_id)
        ->orderByRaw('id = ? desc', [$firstProduct->id])
        ->orderBy('id')
        ->get()
    : ($sameModelProducts ?? collect()))
@php($rolletProfilePricesTitle = 'Цены на секционные ворота')
@php($rolletProfilePricesNote = 'В таблицах указаны цены на популярные размеры секционных ворот по профилям RH45N, RH58N и RH77M. Итоговая стоимость уточняется по размерам, комплектации и монтажу.')

@include('front.subcategory-template-1')
